[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "maxpygame"
version = '0.1.3'
description = "A simple pygame engine"
readme = "readme.md"
requires-python = ">=3.7"
dependencies = ['pygame']